//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VueAdminmanager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        public int GoodsID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> CFID { get; set; }
        public string GoodsName { get; set; }
        public string img { get; set; }
    
        public virtual CFplace CFplace { get; set; }
        public virtual GoodsType GoodsType { get; set; }
    }
}
